// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Provider-neutral telemetry vocabulary shared across Switchyard crates.
//!
//! This module defines the stable string contract for route-selection and
//! Langfuse observations: generic OpenTelemetry attribute keys, Langfuse-native
//! metadata keys, and the allowed values for response origin and call role. It
//! carries only names and values: no instrumentation, exporter, or metric
//! behavior, so any crate can emit or read the same vocabulary without
//! depending on a telemetry backend.

use std::fmt;

/// Generic OpenTelemetry attribute keys for route-selection telemetry.
///
/// Backend-neutral keys an exporter maps onto its own attribute namespace.
/// They are associated `const`s so callers may use them in attribute tables
/// and span metadata without allocation.
pub struct GenericKeys;

impl GenericKeys {
    /// Route the request was sent for.
    pub const ROUTE_ID: &str = "switchyard.route.id";
    /// Routing algorithm that produced the selection.
    pub const ALGORITHM: &str = "switchyard.routing.algorithm";
    /// Target the routing algorithm selected.
    pub const SELECTED_TARGET: &str = "switchyard.routing.selected_target";
    /// Target that actually served the response.
    pub const SERVED_TARGET: &str = "switchyard.response.served_target";
    /// Origin of the served response, one of [`ResponseOrigin`].
    pub const RESPONSE_ORIGIN: &str = "switchyard.response.origin";
    /// Role of the call within the route, one of [`CallRole`].
    pub const CALL_ROLE: &str = "switchyard.call.role";
    /// Target the call was directed at.
    pub const CALL_TARGET: &str = "switchyard.call.target";
}

/// Langfuse-native metadata keys for route-selection observations.
///
/// The literal key strings Langfuse expects on an observation's `metadata`
/// object. `const`s so callers can build observation metadata without
/// allocation.
pub struct LangfuseKeys;

impl LangfuseKeys {
    /// Session identifier that groups an observation.
    pub const SESSION_ID: &str = "langfuse.session.id";
    /// Observation metadata key for the route id.
    pub const ROUTE_ID: &str = "langfuse.observation.metadata.switchyard.route_id";
    /// Observation metadata key for the routing algorithm.
    pub const ALGORITHM: &str = "langfuse.observation.metadata.switchyard.algorithm";
    /// Observation metadata key for the selected target.
    pub const SELECTED_TARGET: &str = "langfuse.observation.metadata.switchyard.selected_target";
    /// Observation metadata key for the served target.
    pub const SERVED_TARGET: &str = "langfuse.observation.metadata.switchyard.served_target";
    /// Observation metadata key for the response origin.
    pub const RESPONSE_ORIGIN: &str = "langfuse.observation.metadata.switchyard.response_origin";
    /// Observation metadata key for the call role.
    pub const CALL_ROLE: &str = "langfuse.observation.metadata.switchyard.call_role";
    /// Observation metadata key for the call target.
    pub const CALL_TARGET: &str = "langfuse.observation.metadata.switchyard.call_target";
}

/// Origin of a served response.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResponseOrigin {
    /// Served by a backing target model.
    Target,
    /// Generated by Switchyard's routing layer rather than a target model.
    RoutingGenerated,
}

impl ResponseOrigin {
    /// Returns the stable contract value for the origin.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Target => "target",
            Self::RoutingGenerated => "routing_generated",
        }
    }
}

impl fmt::Display for ResponseOrigin {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Role a call plays within a routed request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CallRole {
    /// A call Switchyard makes while selecting a route, not for the answer.
    RoutingDependency,
    /// The primary model serving the answer.
    AnswerPrimary,
    /// A fallback model serving the answer.
    AnswerFallback,
}

impl CallRole {
    /// Returns the stable contract value for the role.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::RoutingDependency => "routing_dependency",
            Self::AnswerPrimary => "answer_primary",
            Self::AnswerFallback => "answer_fallback",
        }
    }
}

impl fmt::Display for CallRole {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generic_keys_match_the_contract() {
        assert_eq!(GenericKeys::ROUTE_ID, "switchyard.route.id");
        assert_eq!(GenericKeys::ALGORITHM, "switchyard.routing.algorithm");
        assert_eq!(
            GenericKeys::SELECTED_TARGET,
            "switchyard.routing.selected_target"
        );
        assert_eq!(
            GenericKeys::SERVED_TARGET,
            "switchyard.response.served_target"
        );
        assert_eq!(GenericKeys::RESPONSE_ORIGIN, "switchyard.response.origin");
        assert_eq!(GenericKeys::CALL_ROLE, "switchyard.call.role");
        assert_eq!(GenericKeys::CALL_TARGET, "switchyard.call.target");
    }

    #[test]
    fn langfuse_keys_match_the_contract() {
        assert_eq!(LangfuseKeys::SESSION_ID, "langfuse.session.id");
        assert_eq!(
            LangfuseKeys::ROUTE_ID,
            "langfuse.observation.metadata.switchyard.route_id"
        );
        assert_eq!(
            LangfuseKeys::ALGORITHM,
            "langfuse.observation.metadata.switchyard.algorithm"
        );
        assert_eq!(
            LangfuseKeys::SELECTED_TARGET,
            "langfuse.observation.metadata.switchyard.selected_target"
        );
        assert_eq!(
            LangfuseKeys::SERVED_TARGET,
            "langfuse.observation.metadata.switchyard.served_target"
        );
        assert_eq!(
            LangfuseKeys::RESPONSE_ORIGIN,
            "langfuse.observation.metadata.switchyard.response_origin"
        );
        assert_eq!(
            LangfuseKeys::CALL_ROLE,
            "langfuse.observation.metadata.switchyard.call_role"
        );
        assert_eq!(
            LangfuseKeys::CALL_TARGET,
            "langfuse.observation.metadata.switchyard.call_target"
        );
    }

    #[test]
    fn allowed_values_match_the_contract() {
        assert_eq!(ResponseOrigin::Target.as_str(), "target");
        assert_eq!(
            ResponseOrigin::RoutingGenerated.as_str(),
            "routing_generated"
        );
        assert_eq!(CallRole::RoutingDependency.as_str(), "routing_dependency");
        assert_eq!(CallRole::AnswerPrimary.as_str(), "answer_primary");
        assert_eq!(CallRole::AnswerFallback.as_str(), "answer_fallback");
    }
}
