#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Installs the Switchyard background server as a per-user LaunchAgent and sets
# up a `sy` Codex profile.
#
# Reinstalling keeps the original Codex config backup and regenerates the
# routed config from it.
# Run with --dry-run to print what would happen.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

DRY_RUN=0
case "$#:${1:-}" in
  0:) ;;
  1:--dry-run) DRY_RUN=1 ;;
  *) printf 'Usage: %s [--dry-run]\n' "$0" >&2; exit 2 ;;
esac

# shellcheck source=scripts/macos/common.sh
source "$SCRIPT_DIR/common.sh"

# Builds a whole Codex config that routes through Switchyard, derived from the
# original config.toml. Codex.app cannot use the sy profile.
write_codex_switchyard_config() {
  local source="$1" target="$2"
  if [[ ! -f "$source" ]]; then
    say "  no $source; using an empty baseline"
  fi
  if (( DRY_RUN )); then
    say "  would write $target"
    return
  fi

  local body
  body="$(mktemp)"
  # Drop what this file replaces: the top-level model selection, any
  # model_provider, and an earlier copy of the provider table.
  if [[ -f "$source" ]]; then
    awk '
      BEGIN { preamble = 1; skip_table = 0 }
      /^[[:space:]]*\[/ {
        preamble = 0
        header = $0
        sub(/[[:space:]]*#.*/, "", header)
        skip_table = (header ~ /^[[:space:]]*\[model_providers\.sy\][[:space:]]*$/)
      }
      preamble && /^[[:space:]]*(model|model_provider)[[:space:]]*=/ { next }
      !skip_table { print }
    ' "$source" > "$body"
  else
    : > "$body"
  fi

  {
    echo "# Generated by the Switchyard installer from the existing Codex config."
    echo "model = \"switchyard\""
    echo "model_provider = \"sy\""
    cat "$body"
    echo
    echo "[model_providers.sy]"
    echo "name = \"Switchyard\""
    echo "base_url = \"http://127.0.0.1:$SY_PORT/v1\""
    echo "wire_api = \"responses\""
    echo "requires_openai_auth = true"
  } > "$target"
  rm -f "$body"
  say "  wrote $target"
}

xml_escape_text() {
  printf '%s' "$1" | sed \
    -e 's/&/\&amp;/g' \
    -e 's/</\&lt;/g' \
    -e 's/>/\&gt;/g'
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  say "This installer is for macOS only." >&2
  exit 1
fi

step "Building release binaries"
run cargo build --release --manifest-path "$REPO_ROOT/Cargo.toml" \
  -p switchyard-server

step "Installing binaries into $SY_HOME/bin"
run mkdir -p "$SY_HOME/bin" "$SY_HOME/logs"
run install -m 755 "$REPO_ROOT/target/release/switchyard-server" \
  "$SY_HOME/bin/switchyard-server"

step "Writing server config"
# Keep macOS and Linux on the same routing defaults.
write_once "$SY_HOME/composite.toml" < "$REPO_ROOT/scripts/config/composite.toml"

step "Validating the server config"
if (( DRY_RUN )); then
  say "  would run: $SY_HOME/bin/switchyard-server --config $SY_HOME/composite.toml --dry-run"
else
  "$SY_HOME/bin/switchyard-server" --config "$SY_HOME/composite.toml" --dry-run
fi

step "Writing LaunchAgents"
XML_SY_HOME="$(xml_escape_text "$SY_HOME")"
write_always "$LAUNCH_AGENTS/$SERVER_LABEL.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$SERVER_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$XML_SY_HOME/bin/switchyard-server</string>
    <string>--config</string>
    <string>$XML_SY_HOME/composite.toml</string>
    <string>--host</string>
    <string>127.0.0.1</string>
    <string>--port</string>
    <string>$SY_PORT</string>
    <string>--routing-log-file</string>
    <string>$XML_SY_HOME/routing.jsonl</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>$XML_SY_HOME/logs/server.log</string>
  <key>StandardErrorPath</key>
  <string>$XML_SY_HOME/logs/server.err.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>RUST_LOG</key>
    <string>info</string>
  </dict>
</dict>
</plist>
EOF

step "Loading LaunchAgents"
if (( DRY_RUN )); then
  say "  would reload gui/$UID/$SERVER_LABEL"
else
  launchctl bootout "gui/$UID/$SERVER_LABEL" 2>/dev/null || true
  # bootout returns before the job leaves the domain, and bootstrapping a
  # service that is still shutting down fails with an I/O error.
  for _ in $(seq 50); do
    launchctl print "gui/$UID/$SERVER_LABEL" >/dev/null 2>&1 || break
    sleep 0.1
  done
  launchctl bootstrap "gui/$UID" "$LAUNCH_AGENTS/$SERVER_LABEL.plist"
  say "  loaded $SERVER_LABEL"
fi

step "Adding the sy Codex profile"
# `codex --profile sy` reads ~/.codex/sy.config.toml. A [profiles.sy] table in
# config.toml is legacy config that Codex now refuses to start with, so an
# earlier install of this script has to be cleaned up first.
strip_block "$CODEX_CONFIG" "$PROFILE_START" "$PROFILE_END" "the legacy sy profile" || true

# This profile only changes which router answers. Approval and sandbox
# settings are deliberately left out, so the profile cannot loosen how Codex
# asks before it acts. Set those yourself if you want them.
sed "s/@SY_PORT@/$SY_PORT/g" "$REPO_ROOT/scripts/config/codex.sy.toml" |
  write_with_backup "$CODEX_PROFILE_CONFIG"

step "Building a swap-in config for Codex.app"
# Keep the original config as the source for every generated routed config.
CONFIG_SOURCE="$CODEX_CONFIG"
if [[ -f "$CODEX_DIRECT_CONFIG" ]]; then
  CONFIG_SOURCE="$CODEX_DIRECT_CONFIG"
elif [[ -f "$CODEX_CONFIG" ]]; then
  if codex_config_uses_switchyard "$CODEX_CONFIG"; then
    say "  no original config backup found; preserving the current routed config"
  elif (( DRY_RUN )); then
    say "  would snapshot config.toml to $CODEX_DIRECT_CONFIG"
    CONFIG_SOURCE="$CODEX_DIRECT_CONFIG"
  else
    cp "$CODEX_CONFIG" "$CODEX_DIRECT_CONFIG"
    say "  snapshotted config.toml to $CODEX_DIRECT_CONFIG"
    CONFIG_SOURCE="$CODEX_DIRECT_CONFIG"
  fi
else
  if (( DRY_RUN )); then
    say "  would create an empty direct-config baseline at $CODEX_DIRECT_CONFIG"
    CONFIG_SOURCE="$CODEX_DIRECT_CONFIG"
  else
    mkdir -p "$(dirname "$CODEX_DIRECT_CONFIG")"
    : > "$CODEX_DIRECT_CONFIG"
    say "  created an empty direct-config baseline at $CODEX_DIRECT_CONFIG"
    CONFIG_SOURCE="$CODEX_DIRECT_CONFIG"
  fi
fi
write_codex_switchyard_config "$CONFIG_SOURCE" "$CODEX_SWITCHYARD_CONFIG"
if (( DRY_RUN )); then
  say "  would replace $CODEX_CONFIG with $CODEX_SWITCHYARD_CONFIG"
else
  cp "$CODEX_SWITCHYARD_CONFIG" "$CODEX_CONFIG"
  say "  replaced $CODEX_CONFIG with the Switchyard config"
fi

step "Done"
say "Server:   http://127.0.0.1:$SY_PORT  (logs in $SY_HOME/logs)"
say "Use it with: codex -p sy (requires Codex CLI 0.134.0 or newer)"
say ""
if [[ -f "$CODEX_DIRECT_CONFIG" ]]; then
  say "Codex.app is routed. Its original config is backed up at:"
  say "  $CODEX_DIRECT_CONFIG"
else
  say "Codex.app is routed, but no original config backup was available."
fi
say "Restart Codex.app to load the updated config."
